# -------- BUILD STAGE --------
FROM eclipse-temurin:21-jdk AS builder

WORKDIR /usr/src/app

# Copy gradle wrapper & build files first (caching)
COPY gradlew ./
COPY gradle ./gradle
COPY settings.gradle* build.gradle ./

RUN chmod +x gradlew

# Copy the application source
COPY . .

# Build the app
RUN ./gradlew installDist

# -------- RUNTIME STAGE --------
FROM eclipse-temurin:21-jre

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/build/install /usr/src/app/build/install

ENV AD_PORT=9099
EXPOSE 9099

ENTRYPOINT ["./build/install/opentelemetry-demo-ad/bin/Ad"]
