FROM python:3.12-slim-bookworm AS base

WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT [ "python", "recommendation.py" ]